# This is a basic workflow to help you get started with Actions

name: test_workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  invader_array:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Step 1 
        run: echo "The full invaders array should include the three types of aliens."

      - name: Step 2
        run: echo "These should move from side to side, and fire at the player at random."
          
      - name: Step 3
        run: echo "Their speed of movement should increase as the invaders are reduced in number (from being shot)."
  
  defender_action:

      runs-on: windows-latest
      
      steps:

        - uses: actions/checkout@v4
        
        - name: Step 1
          run: echo "The defender (player) should be able to shoot multiple bullets continuously."
        
        - name: Step 2 
          run: echo "Implement collision detection so that invaders are destroyed when successfully shot by the player."
        
        - name: Step 3
          run: echo "Player loses a life and respawns (until run out of lives) when shot by an invader."

  green_barriers:

      runs-on: windows-latest

      steps:

        - uses: actions/checkout@v4

        - name: Requirement
          run: echo "The four green barriers should diminish every time they are shot by both the invaders and the defender/player."



          
      
  
    
